package usersThatCanDrink;

import InputUtils.InputUtils;

public class Main {
    public static void main(String[] args) {
        System.out.println(
                "Bem vindo!Neste programa você irá inserir até 5 usuários, e saberá quais deles tem idade pra beber!");
        User[] users = receiveInitialInput();
        printUsersThatCanDrink(users);
    }

    /**
     * Prints which users can drink.
     * 
     * @param users list of users
     */
    public static void printUsersThatCanDrink(User[] users) {
        System.out.println("Gerando a lista de usuários (" + User.totalUsers + " usuário(s)!):");
        for (User user : users) {
            if (user != null) {
                if (user.canDrink())
                    System.out.println(user.name + " tem " + user.age + " aninhos e já pode encher a cara!");
            }
        }
    }

    /**
     * Reads initial input from the user, so that we can define our users
     * 
     * @return an array of users generated by the user
     */
    public static User[] receiveInitialInput() {
        User[] usersInput = new User[5];
        final int MAX_USERS = 5;
        for (int i = 0; i < MAX_USERS; i++) {

            String name = User.formatName(InputUtils.getStringInput("Por favor insira o nome do usuário nº " + (i + 1)));
            int age = InputUtils.getIntInput("Por favor insira a idade do(a) " + name);
            usersInput[i] = new User(name, age);

            if (i != 4 && createNextUserCheck(i) == false)
                break;
        }
        return usersInput;

    }

    /**
     * Checks if the user is done creating users or wants to create some more
     * 
     * @param i used to know what number to show up on the log message
     * @return a boolean indicating if the user wants to create a new user or not
     */
    public static boolean createNextUserCheck(int i) {
        String decision = InputUtils.getStringInput("(Y/N) Deseja cadastrar outro usuário? Cadastrados até agora: " + (i + 1) + "/5");
        return (decision.equalsIgnoreCase("Y"));
    }
}
